name: Email Auto-Response Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  check-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug
        run: |
          echo "GMAIL_TOKEN_JSON exists: ${{ secrets.GMAIL_TOKEN_JSON != '' }}"
          echo "DEEPSEEK_API_KEY exists: ${{ secrets.DEEPSEEK_API_KEY != '' }}"
      - name: Run email bot
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
        run: python main.py
